// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace cpGames.VSA
{
    internal sealed partial class Vsix
    {
        public const string Id = "VSA.f705a1a6-5207-4496-ad4f-a7b8a52eebd1";
        public const string Name = "VSA";
        public const string Description = @"Your friendly AI programmer.";
        public const string Language = "en-US";
        public const string Version = "0.1";
        public const string Author = "ChillPillGames";
        public const string Tags = "AI";
    }
}
