// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace cpGames.VSA
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string VSAGuidString = "cb8cf9fb-11eb-4b63-aba2-6133d16f82f0";
        public static Guid VSAGuid = new Guid(VSAGuidString);

        public const string GuidIconString = "64671dd8-4e7c-4db4-86a5-5c16e9845b15";
        public static Guid GuidIcon = new Guid(GuidIconString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int ShowVSACommand = 0x0100;
        public const int Icon = 0x0001;
    }
}