// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace cpGames.VSA
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string VSAGuidString = "cb8cf9fb-11eb-4b63-aba2-6133d16f82f0";
        public static Guid VSAGuid = new Guid(VSAGuidString);

        public const string GuidLogoString = "4946c84e-c4c9-45db-b1f7-ea362214b738";
        public static Guid GuidLogo = new Guid(GuidLogoString);

        public const string GuidPreviewString = "786dc029-63fa-444a-8255-7f3ade06bacf";
        public static Guid GuidPreview = new Guid(GuidPreviewString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int ShowVSACommand = 0x0100;
        public const int Logo = 0x0001;
        public const int Preview = 0x0001;
    }
}